-- =============================================
-- Generated by ForgeSQL
-- Database: PostgreSQL
-- Generated at: 2026-02-25T00:49:23.080Z
-- =============================================

-- =============================================
-- TABLES
-- =============================================

CREATE TABLE "employees" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "first_name" VARCHAR(100) NOT NULL,
  "last_name" VARCHAR(100) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "is_active" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pk_employees" PRIMARY KEY ("id")
);

CREATE TABLE "teams" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(100) NOT NULL UNIQUE,
  "description" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pk_teams" PRIMARY KEY ("id")
);

CREATE TABLE "salary_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_id" INTEGER NOT NULL,
  "amount" DECIMAL(15,2) NOT NULL,
  "currency" VARCHAR(3) NOT NULL,
  "effective_date" DATE NOT NULL,
  "end_date" DATE,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pk_salary_history" PRIMARY KEY ("id")
);

CREATE TABLE "employee_team_assignments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_id" INTEGER NOT NULL,
  "team_id" INTEGER NOT NULL,
  "start_date" DATE NOT NULL,
  "end_date" DATE,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pk_employee_team_assignments" PRIMARY KEY ("id")
);

-- =============================================
-- FOREIGN KEY CONSTRAINTS
-- =============================================

ALTER TABLE "employee_team_assignments" ADD CONSTRAINT "fk_employee_team_assignments_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "employee_team_assignments" ADD CONSTRAINT "fk_employee_team_assignments_team_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "salary_history" ADD CONSTRAINT "fk_salary_history_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
